.TH LIBPARSEPCF 7 LIBPARSEPCF
.SH NAME
libparsepcf \- Library for interpreting PCF (Portable Compiled Format) font files

.SH DESCRIPTION
.B libparsepcf
is a C library for interpreting PCF (Portable Compiled Format) font
files. It can be used to examine the contents of a font file. It does not render
text, instead the user is given enough information to implement it's own
rendering; nor is the library capable of creating PCF files.

.SH SEE ALSO
.BR libparsepcf.h (0),
.BR libparsepcf_get_tables (3),
.BR libparsepcf_preparse_font (3)
